### ISSUE TITLE
这个SDK有一个严重的安全问题

### ISSUE THREAD

**Issue by CaveyChan** [qiniu/react-native-sdk#13]
SDK要求配置ACCESS_KEY、SECRET_KEY  如下
import Qiniu,{Auth,ImgOps,Conf,Rs,Rpc} from 'react-native-qiniu';
Conf.ACCESS_KEY = <AK>
Conf.SECRET_KEY = <SK>

这会误导使用者，
直接写在JS，如果APP被反编译，会引发严重的安全问题，
建议去掉。

**Comment by buhe** [comment]
恩，是一定要在服务器端获取，不过我把这部分的工作实际上交给了 客户端程序员自己去解决，因为我觉得这不是 SDK 要实现的功能。
这样，我在文档里面注明一下，强烈建议用户不要把 KEY 保存在本地。你觉得如何？

**Comment by buhe** [comment]
import Qiniu,{Auth,ImgOps,Conf,Rs,Rpc} from 'react-native-qiniu';
Conf.ACCESS_KEY = <AK>
Conf.SECRET_KEY = <SK>
//强烈不建议在客户端保存 AK 和 SK ，反编译后 hacker 获取到可以对你的资源为所欲为，建议通过安全渠道从服务器端获取。

如何？

**Comment by CaveyChan** [comment]
除了提示信息，建议你把那些生成token的函数去掉。这样最安全。

**Comment by tans** [comment]
按照我的理解, AK和SK是不应该在客户端直接获取, 应该是服务器直接根据

**Comment by tans** [comment]
根据我的理解, AK和SK是不用在客户端获取的, 而是客户端传送flags的信息到服务器, 在服务器上面实现token的计算返回客户端的,然后再在客户端继续后续的操作. 是这样子吗?
`
    token() {
      var flags = this.getFlags(); //这是客户端上传, 其他下面的都在服务器上面实现.
      var encodedFlags = urlsafeBase64Encode(JSON.stringify(flags));
      var encoded = hmacSha1(encodedFlags, conf.SECRET_KEY);
      var encodedSign = base64ToUrlSafe(encoded);
      var uploadToken = conf.ACCESS_KEY + ':' + encodedSign + ':' + encodedFlags;
      return uploadToken;
    }
`

**Comment by buhe** [comment]
没错

**Comment by fenglu09** [comment]
个人认为客户端不应该获取AK和SK，token应该直接请求服务器获取
