### ISSUE TITLE
上传图片：TypeError: Network request failed

### ISSUE THREAD

**Issue by elyonsaber** [qiniu/react-native-sdk#15]
`  upload() {
    var uptoken = <token>;

    let formInput = {
      key: "testreactnative.jpg",
    }

    Rpc.uploadFile("http://www.kiodev.com/wp-content/uploads/2016/03/react-logo.png", uptoken, formInput) 
      .then((response) => response.text())
      .catch((error) => {
        console.warn("error", error);
      });
  }`
uptoken是获取后使用的
安卓上传始终报错error  [TypeError: Network request failed],请问该如何解决呢，是我设置不对吗，谢谢！

**Comment by buhe** [comment]
http://www.kiodev.com/wp-content/uploads/2016/03/react-logo.png
这是什么？

**Comment by buhe** [comment]
上传本地文件，在线文件上传不支持

**Comment by elyonsaber** [comment]
好的谢谢，我试下，是参考你之前的[https://github.com/buhe/present-demo/blob/master/presentdemo/ImageSelected.js](demo)写的

**Comment by elyonsaber** [comment]
试了下成功了，一开始错误理解了，谢谢
