### ISSUE TITLE
刚刚您说的Bucket字段和文件的key是在哪里可以获取的吗

### ISSUE THREAD

**Issue by xudao520** [qiniu/react-native-sdk#2]
![image](https://cloud.githubusercontent.com/assets/12093709/15644512/135d71e8-2686-11e6-9e52-c13006a545df.png)
 我用react-native-image-picker 插件获取到image，但是貌似没有文件的key和Bucket，能详细介绍下吗？

**Comment by xudao520** [comment]
@buhe

**Comment by buhe** [comment]
hi 你好，key 是你自己决定的，也就是七牛这边实际帮你存储的文件名。  bucket 是在七牛的后台创建的。相当于一个空间 名称。
myImages:baby.png
可能最终就是这样的了

**Comment by xudao520** [comment]
@buhe ok，谢谢

**Comment by xudao520** [comment]
![image](https://cloud.githubusercontent.com/assets/12093709/15645127/5d8fb99e-2689-11e6-887c-3c6ae219694c.png)
@buhe 是不是不能使用localhost的？

**Comment by xudao520** [comment]
@buhe 我模拟器跑上传图片都会提示网络出问题，是不是不能使用本地的

**Comment by xudao520** [comment]
已经好了，谢谢
