### ISSUE TITLE
无法覆盖上传

### ISSUE THREAD

**Issue by lentg** [qiniu/react-native-sdk#20]
文件上传指定backet:key无法覆盖已存在的文件。

**Comment by jlala** [comment]
上传同一个文件，但是在app里面选择的时候会改变文件的rui，导致key每次都不一样，上传完后无法覆盖文件 怎么解决呢？

**Comment by buhe** [comment]
在构建 FormInput 的时候，传入 key 字段就可以了

**Comment by buhe** [comment]
let formInput = {
    key : "<Key>",
    // formInput对象如何配置请参考七牛官方文档“直传文件”一节
}
