### ISSUE TITLE
使用Rpc.uploadFile是无法获取 promise的内容吗？无法知道是否正确上传呢？

### ISSUE THREAD

**Issue by jlala** [qiniu/react-native-sdk#23]
var fetchupload = Rpc.uploadFile(uri, uptoken, formInput);

输出fetchupload 为：Promise { _45: 0, _81: 0, _65: null, _54: null }

怎么可以简单知道我上传成功了呢？

**Comment by buhe** [comment]
hey man,
Rpc.uploadFile(uri, uptoken, formInput).then((resp)=>{})

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
