### ISSUE TITLE
这么久不更新了，现在使用这个插件直接报错 TypeError: Network request failed(…)，请求没办法发出去！

### ISSUE THREAD

**Issue by daffy6537** [qiniu/react-native-sdk#25]
看了源码，给option加了‘POST’，也不行

**Comment by daffy6537** [comment]
在issue中找到解决办法了，用了

用superagent 重写上传部分,支持上传进度 enhancement help wanted

感谢@cdmalcl

**Comment by cdmalcl** [comment]
不客气 实在忙成狗！希望能有人整出全套的版本和demo！
