### ISSUE TITLE
直传文件时，有没有经常收到服务器返回UP/400的错误

### ISSUE THREAD

**Issue by CecilLee** [qiniu/react-native-sdk#26]
发现upload.qiniu.com经常返回UP/400的错误，

我这边修改了代码，把使用fetch改成了使用XmlHttpRequest，
然后在onreadystatechange中，监测readyState的变化，发现出错时，readyState总是停留在1上面了，还没有到达2,3,4。

也就是刚刚建立连接，还在发送数据中，数据还没有发送完成，服务端就关闭了连接并返回了UP/400错误。

**Comment by buhe** [comment]
thanks 我去定位一下

**Comment by buhe** [comment]
能否提供一下 rn 的版本?

**Comment by CecilLee** [comment]
RN版本 0.39

**Comment by buhe** [comment]
0.39 是 rn 底层的问题。考虑升级一下

**Comment by jlala** [comment]
请问这个问题有解决吗？

**Comment by buhe** [comment]
@jlala 请升级到 0.40 + 版本，你现在的版本是？

**Comment by buhe** [comment]
sdk 升级到 0.3.0 ，使用了 xhr 做传输，并且支持了 progress callback

**Comment by buhe** [comment]
如果有问题 reopen issue

**Comment by lucifer-cw** [comment]
RN 0.40版本，依然上传经常 400
