### ISSUE TITLE
[IOS]调用upLoadFile时，服务器返回400

### ISSUE THREAD

**Issue by johnbryant** [qiniu/react-native-sdk#27]
rn版本：0.39.2

![image](https://cloud.githubusercontent.com/assets/5527451/21707041/c65699fe-d406-11e6-9236-615ceabbbf71.png)

![image](https://cloud.githubusercontent.com/assets/5527451/21707059/e2c2f22c-d406-11e6-835f-531bbd6cad4a.png)

**Comment by johnbryant** [comment]
![image](https://cloud.githubusercontent.com/assets/5527451/21707684/5201aff2-d40c-11e6-8c62-950a59068479.png)

这是formInput里的内容。

**Comment by CecilLee** [comment]
是的，我也遇到这个问题了，请问你解决了吗

**Comment by buhe** [comment]
@CecilLee 试一下新的版本 3.0

**Comment by CecilLee** [comment]
@buhe xhr也是不可以的，400错误一定会有。

但也不能确定是0.39.2的问题，

400错误是服务端报告的吧

**Comment by CecilLee** [comment]
这个问题应该是qiniu的服务端的问题

**Comment by buhe** [comment]
未必是服务器问题，是 payload 的问题，这个问题我们定位过了，0.39 有一定几率发送错误的 payload

**Comment by johnbryant** [comment]
@buhe 表示用了3.0上传没成功过，一直报这个错
![image](https://cloud.githubusercontent.com/assets/5527451/22023891/0342cc2a-dd03-11e6-8708-13c7d6144204.png)

**Comment by johnbryant** [comment]
还是用的2.0版本，上传之前把图片压缩了一下，就很少出问题了

**Comment by chuangbo** [comment]
我是 0.40，大概率遇到 400 错误，偶尔 200 ok

**Comment by chuangbo** [comment]
应该是 React Native xhr API 的问题，更换为 [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) 后问题解决。

```js

import Qiniu from 'react-native-qiniu';
import RNFetchBlob from 'react-native-fetch-blob';

/**
 * Use react-native-fetch-blob to fix large file issue
 */
export function uploadFile(uri, token, formInput) {
  if (typeof formInput.type == 'undefined') {
    formInput.type = 'application/octet-stream';
  }

  if (typeof formInput.name == 'undefined') {
    var filePath = uri.split("/");
    if (filePath.length > 0) {
      formInput.name = filePath[filePath.length - 1];
    } else {
      formInput.name = "";
    }
  }

  return RNFetchBlob.fetch('POST', Qiniu.Conf.UP_HOST, {
    'Content-Type' : 'multipart/form-data',
  }, [
    { name: 'file', filename: formInput.name, type: formInput.type, data: RNFetchBlob.wrap(uri)},
    { name : 'key', data : formInput.key},
    { name : 'token', data : token},
  ]);
}

```

**Comment by jlala** [comment]
@johnbryant 上传之前把图片压缩 在rn里面用了什么组件 压缩的？

**Comment by jlala** [comment]
你们 使用七牛 rn版本 上传图片速率是多少？

**Comment by johnbryant** [comment]
@jlala react-native-image-resizer

**Comment by mataoct** [comment]
@chuangbo 你的策略是对的，但是好像传的参数有问题，按照七牛的Form构造文档

```
return RNFetchBlob.fetch('POST', Qiniu.Conf.UP_HOST, {
    'Content-Type' : 'multipart/form-data',
  }, [
    { name: 'file', data:{uri: uri, type: formInput.type, name: formInput.name} },
    { name : 'key', data : formInput.key},
    { name : 'token', data : token},
  ])
```
这样才能成功，否则会引起闪退

**Comment by iOSHw** [comment]
up是不准备更新这个bug了吗？最佳解决方案是什么？ @buhe
