### ISSUE TITLE
使用七牛直传的时候，如果我想让七牛自动给我生成文件key，怎么做？

### ISSUE THREAD

**Issue by CaveyChan** [qiniu/react-native-sdk#3]
如题
这个SDK的上传接口，必须指定key，希望让七牛自动给我生成文件key，怎么做？

**Comment by buhe** [comment]
暂时不支持，下个版本应该会加上，如果急用可以自己改一下 提 pull request 给我

**Comment by CaveyChan** [comment]
新提交的PR支持这种需求

**Comment by buhe** [comment]
0.1.1 版本已经发布到 npm
