### ISSUE TITLE
rpc.js 数据校验的reject返回值应该有提示比较好？

### ISSUE THREAD

**Issue by ds009** [qiniu/react-native-sdk#32]
在rpc.js里面这一段如果没看源码的话容易收到null作为返回结果，不便debug，能否加个提示消息？谢谢啦
> if (typeof uri != 'string' || uri == '' || typeof formInput.key == 'undefined') {
      reject && reject(null);
      return;
    }

**Comment by buhe** [comment]
send pr be free :)
