### ISSUE TITLE
关于上传不成功的一些tips(Some Tips for the failure of uploading)

### ISSUE THREAD

**Issue by monzy613** [qiniu/react-native-sdk#36]
1. 请用真机, 我用iOS模拟器上传了半天一直报invalid multipart format: multipart: NextPart: EOF这样的错
Please use real device, I tried it for a whole night on iOS simulator and it always failed with error like this: 
invalid multipart format: multipart: NextPart: EOF
anyone know why, please tell me. thanks.
2. 这个sdk里面有用的代码其实是rpc, 具体代码我直接贴在下面
也就是说其实那些conf.accesskey, secretKey根本不用让客户端接触到， 服务端下发下来都不好，我抓个包啥都有了， 最好就是服务端直接把上传图片的token生成了给你传过来， 这样别人才拿不到你的accesskey和secretkey
below is the uploadFile function, you need your local file uri, a key for the file, and a token generated by the key , you can use your server to generate the token.
```javaScript
const uploadFile = ({ uri, token, key, onprogress }) => {
  const formInput = { key }
  return new Promise((resolve, reject)=> {
    if (typeof uri != 'string' || uri == '' || typeof formInput.key == 'undefined') {
      reject && reject(null)
      return;
    }
    if (uri[0] == '/') {
      uri = "file://" + uri
    }
    const xhr = new XMLHttpRequest();
    xhr.open('POST', QINIU_UPLOAD_HOST)
    xhr.onload = () => {
      if (xhr.status !== 200) {
        reject && reject(xhr)
        return
      }

      resolve && resolve(xhr)
    };

    const formdata = new FormData()
    formdata.append("key", formInput.key)
    formdata.append("token", token)
    if (typeof formInput.type == 'undefined') {
      formInput.type = 'application/octet-stream'
    }
    if (typeof formInput.name == 'undefined') {
      const filePath = uri.split("/")
      if (filePath.length > 0) {
        formInput.name = filePath[filePath.length - 1]
      } else {
        formInput.name = ''
      }
    }
    formdata.append("file", {
      uri,
      type: formInput.type,
      name: formInput.name
    })
    xhr.upload.onprogress = (event) => {
      onprogress && onprogress(event, xhr)
    };
    xhr.send(formdata)
  })
}
```
p.s. 注意这里面的QINIU_UPLOAD_HOST，这个sdk里面写死的 http://upload.qiniu.com  然而我最近申请的是华南的区间， 上传的host应该是 http://upload-z2.qiniu.com， 具体的我发工单问过七牛客服，反馈如下：
ATTENTION: the QINIU_UPLOAD_HOST above is not just http://upload.qiniu.com, it depends on the Qiniu Location you apply, and the location - url info is like below you should change your QINIU_UPLOAD_HOST correspond to the location you applied:

您好，http 上传华南入口如下 (South of China, http)
http://up-z2.qiniu.com
上传源站 HTTP 地址, 适用于服务器端上传(good for server-side upload)
http://upload-z2.qiniu.com、
上传 HTTP 加速地址, 适用于客户端上传(good for client-side upload)
https 上传华南入口如下(South of China, https)
https://up-z2.qbox.me
上传源站 HTTPS 地址, 适用于服务器端上传(good for server-side upload)
https://upload-z2.qbox.me
上传 HTTPS 加速地址, 适用于客户端上传(good for client-side upload)

if your apply-location is not South of China, just use http://upload.qiniu.com for QINIU_UPLOAD_HOST 

最后，上传不成功请务必真机调试，我觉得是不是文件系统的原因导致模拟器上没读取到？懂得大佬帮忙看下吧

**Comment by myfailemtions** [comment]
Hello monzy can you share your full code pls

**Comment by monzy613** [comment]
@myfailemtions 
here is how to use:
```javascript
      uploadFile({ uri, token, key })
      .then(result => result)
      .catch(error => console.warn(error))
```

here the uploadFile is the function above. And the function need a parameter like this:
```json
{
  "uri": "file://path/to/the/file",
  "token": "the token generated from qiniu sdk with the same key as below",
  "key": "the key for the file, the token need this key to be generated"
}
```

**Comment by myfailemtions** [comment]
Thank you very much)
