### ISSUE TITLE
为什么直传时，响应信息没有和官网说的不一样？？？

### ISSUE THREAD

**Issue by CaveyChan** [qiniu/react-native-sdk#4]
这是使用这个SDK的返回信息
![8](https://cloud.githubusercontent.com/assets/16031190/15775704/faf3d218-29b5-11e6-846b-ff225df90c7b.png)

这是官网说的
![0739](https://cloud.githubusercontent.com/assets/16031190/15775721/19f0dfe4-29b6-11e6-9110-596fed5db518.png)

 为什么不一样？？？
key 和hash在哪里？？？

**Comment by CaveyChan** [comment]
自己解决了..

**Comment by czzweb** [comment]
@CaveyChan 怎么解决的..
