### ISSUE TITLE
建议把onresp(response);的结果返回

### ISSUE THREAD

**Issue by CaveyChan** [qiniu/react-native-sdk#5]
这样我们就可以以async/await的方式操作uploadImage方法返回的结果，否则调用uploadImage方法返回的是undefined

![00000](https://cloud.githubusercontent.com/assets/16031190/15809720/c6829e82-2bc8-11e6-9e3b-7d049760d2c9.png)

**Comment by buhe** [comment]
建议非常棒，你可以提交 pull request 么?

**Comment by CaveyChan** [comment]
需要pull request吗？
你在onresp(response);前加个return就行了吧

**Comment by CaveyChan** [comment]
或者把onresp(response);两边的{}去掉也行

**Comment by buhe** [comment]
```
exports.post = function (uri, adminToken,content) {
  var headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
  };
  let payload = {
    headers: headers,
    method: 'POST',
    dataType: 'json',
    timeout: conf.RPC_TIMEOUT,
  };
  if(typeof content === 'undefined'){
    payload.headers['Content-Length'] = 0;
  }else{
    //carry data
    payload.body = content;
  }

  if (adminToken) {
    headers['Authorization'] = adminToken;
  }

  return fetch(uri, payload);
}
```

恩。 我别的地方都是这样写的。直接return 会比较好。 这里需要统一一下。 之所以 没敢改 是因为在搞别的东西。 没时间 好好测试一下。另外 document 也需要更新一下， 如果你测试了没问题，还愿意帮助我，可以提 pr ，谢谢

**Comment by buhe** [comment]
应该就不需要 onresp  这个callback 了

**Comment by CaveyChan** [comment]
前段时间比较忙，刚提交了自己的PR，你看看什么地方需要改进

**Comment by buhe** [comment]
非常棒，多谢
