### ISSUE TITLE
用superagent 重写上传部分,支持上传进度

### ISSUE THREAD

**Issue by mozillo** [qiniu/react-native-sdk#6]
在做聊天发送图片 挺需要这个功能的

**Comment by buhe** [comment]
感谢反馈，容我研究一下

**Comment by buhe** [comment]
目前 fetch API 不支持 progress， 这里需要用 xhr 重写一下 。 而且 这部分计划要支持 promise ，现在这种 callback 的形式不够好， 你有兴趣帮忙 重写一下这部分么？ 

var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://posttestserver.com/post.php');
    xhr.onload = () => {
      if (xhr.status !== 200) {
        AlertIOS.alert(
          'Upload failed',
          'Expected HTTP 200 OK response, got ' + xhr.status
        );
        return;
      }

      // upload succeeded
      ...
    };
    var formdata = new FormData();
    formdata.append(photo, {type: "image/jpeg", name: ____, uri: ______ });

    if (xhr.upload) {
      xhr.upload.onprogress = (event) => {
        console.log('upload onprogress', event);
        if (event.lengthComputable) {
          this.setState({uploadProgress: event.loaded / event.total});
        }
      };
    }
    xhr.send(formdata);

要改成这种，但是要支持 promise

**Comment by buhe** [comment]
还有个思路，修改 fetch ，提交 pr 给react-native

**Comment by Pikaurd** [comment]
fetch应该是标准实现，我觉得改fetch不可行

**Comment by buhe** [comment]
@Pikaurd  对，这个不太合适，可能还是要用 xhr 重写

**Comment by buhe** [comment]
@Pikaurd 你还有什么更好的建议么？我觉得用 xhr 重写 还挺蛋疼的

**Comment by Pikaurd** [comment]
@buhe 没有……我刚才看了下[fetch](https://fetch.spec.whatwg.org), 估计过段时间会加上进度

**Comment by buhe** [comment]
@Pikaurd 
如果标准即将支持是 可以试试给 RN 提 pr的，看看他们是不是能接受。 重新用 xhr 造个跟 fetch 类似的东西 感觉好奇怪.

**Comment by Pikaurd** [comment]
@buhe 
你看第六节
> The fetch() method is relatively low-level API for fetching resources. It covers slightly more ground than XMLHttpRequest, although it is currently lacking when it comes to request progression (not response progression).
他也没说啥时候加，着急用就自己做了吧，又或者用原生实现？反正都不省心

**Comment by buhe** [comment]
If you want to receive the body data progressively:
```
function consume(reader) {
  var total = 0
  return pump()
  function pump() {
    return reader.read().then(({done, value}) => {
      if (done) {
        return
      }
      total += value.byteLength
      log(`received ${value.byteLength} bytes (${total} bytes in total)`)
      return pump()
    })
  }
}

fetch("/music/pk/altes-kamuffel.flac")
  .then(res => consume(res.body.getReader()))
  .then(() => log("consumed the entire body without keeping the whole thing in memory!"))
  .catch(e => log("something went wrong: " + e))
```
应该是这东西吧

**Comment by Pikaurd** [comment]
这下载进度

**Comment by buhe** [comment]
var r = request
            .post(this.props.uploadUrl)
            .field('key', key)
            .field('token', this.props.token)
            .field('x:filename', file.name)
            .field('x:size', file.size)
            .attach('file', file, file.name)
            .set('Accept', 'application/json');
        if (isFunction(file.onprogress)) { r.on('progress', file.onprogress); }

计划用 superagent 替代 fetch ，改动不会太大，也可以用 promise

**Comment by cdmalcl** [comment]
还是不行...

**Comment by cdmalcl** [comment]
cei！忘加：'file:///'+ 了....

**Comment by buhe** [comment]
可以了么？如果可以，你可以尝试 提一个 pr 和 demo ，我这边也测试一下。 然后 merge 进来

**Comment by cdmalcl** [comment]
在安卓上测试通过了 这几天不忙的话就弄弄

**Comment by cdmalcl** [comment]
![Uploading picimage (1).png…]()
![Uploading picimage.png…]()


android的例子做好了 这两天抽空测试ios并上传上来

**Comment by buhe** [comment]
你真棒 @cdmalcl ，有空 pr 。多谢

**Comment by cdmalcl** [comment]
@buhe 最近太忙 例子等ios的调试好一起上吧

**Comment by jlala** [comment]
@cdmalcl 请问 qiniu 上传demo 可以提供一个地址吗？

**Comment by jlala** [comment]
以上方法 ios中可以 在加一个 
xhr.upload.addEventListener("progress", function(evt) {
    if (evt.lengthComputable) {
      var nowDate = new Date().getTime();
      taking = nowDate - startDate;
      var x = (evt.loaded) / 1024;
      var y = taking / 1000;
      var uploadSpeed = (x / y);
      var formatSpeed;
      if (uploadSpeed > 1024) {
          formatSpeed = (uploadSpeed / 1024).toFixed(2) + "Mb\/s";
      } else {
          formatSpeed = uploadSpeed.toFixed(2) + "Kb\/s";
      }
      var percentComplete = Math.round(evt.loaded * 100 / evt.total);
      $('.progress-label').text(percentComplete + '%');
    }
  }, false);
这样的方法 应该进度也能显示 七牛的web直传方法

**Comment by cdmalcl** [comment]
最近忙的像条狗 对不住啊 我现在简单弄下

**Comment by cdmalcl** [comment]
[qnrneg.zip](https://github.com/qiniu/react-native-sdk/files/608371/qnrneg.zip)

**Comment by buhe** [comment]
thanks all. 

v0.3.0  已经和入了 progress callback
